### ISSUE TITLE
Comparison of object and null is inconsistent

### ISSUE THREAD

**Issue by FilipDolnik** [kondziu/FML#1]
Comparison (== and !=) operators for custom object and null break equality symmetry. 

For example:
```
let obj = object begin end;

print("~\n", obj == null); // true
print("~\n", null == obj); // false
```

The expected behavior in this case is for both to be false.

**Comment by kondziu** [comment]
Thanks!

It's a dispatch problem: since `obj` does not define `==`, `==` is executed from its parent, which is `null` and `null` == `null`. This will also have other weird related behaviors.

**Comment by martin-t** [comment]
Here's something probably related:

```
let i = object extends 5 begin end;
print("~\n", i == 5); // prints true
print("~\n", 5 == i); // prints false
```

In a way, I am not sure what the expected behavior is - `5` shouldn't have to know how to compare itself to its subclasses.

**Comment by kondziu** [comment]
Yup. It's the same problem. Well spotted. Eventually to be fixed.

**Comment by kondziu** [comment]
Fixed.

**Comment by kondziu** [comment]
I implemented a default eq for objects and arrays. That's a bad way of solving it, since the comparison overlooks a custom compare method for child objects in object instances and arrays. 

I think it should short-circuit instead.

**Comment by FilipDolnik** [comment]
I think this can be solved like in JVM. By having a default implementation of equals in Object (parent of all classes). Except here we have a Unit type (null) but it has the same role. The default implementation will compare only by object identity (the same memory address for example).

The only other requirement is for the Unit object to be a singleton (or having the same identity). 

This could be further improved by adding an identity comparison operator (for example ===) and having the equals call this operator by default.

Note that because integers are not primitives in this language (as far as I know), they will need special treatment. 
And arrays also should have a different default implementation that compares by size and then by each element.

**Comment by kondziu** [comment]
Ok, so I gave this a lot of thought and I decided to punt.

The asymmetry is not a problem. It's strictly a result of the semantics: `x == null` is equivalent to `x.==(null)` which is not the same as `null.==x`, philosophically speaking. For example, if you overload `==`, the operation will remain asymmetrical regardless of what the interpreter does.

The problem is that all objects are a subclass of `null`. That doesn't really make sense: objects are not instances of null with additional behavior. An object whose parent is null should instead be interpreted as an object without a parent. In that case there is still asymmetry, but the behavior of dispatch would be to error out, which makes more sense.

This has the added advantage of being easier to implement, which is really high on my list of objectives for the semantics.
