### ISSUE TITLE
Label -- Unique-problem

### ISSUE THREAD

**Issue by D1zzlaster** [kondziu/FML#6]
After disecting a fml program 
```
function a() -> 5
print("~\n", a()) 
```

(using v2 of fml compiler) the bytecode contains the instruction `label indexcp01 (00 01 00)` twice.
To be more precise, the body of function `a` is "copied" inside the body of "main" function (λ:)

Included in the zip file is the fml source (with possible extra semicolons, woops), the compiled bytecode and two disected .txt files -- one is pure bytecode, only "formatted" a bit, the second one is human readable version of said bytecode.

[fncinsideprint.zip](https://github.com/kondziu/FML/files/6172555/fncinsideprint.zip)

**Comment by kondziu** [comment]
After some examination, it would appear this bug is an issue with how the compiler lays out functions in the code vector. Each function is wrongly assumed to be a part of the main function. So during serialization each function is serialized separately, and their code is also included in the code for main. 

By a happy? accident, this works anyway. Since the functions are copied, whichever label you jump into will lead to a correct execution.

The fix is a bit complicated and since I painted myself into a corner with how serialization works, I need a day or two to fix this.

**Comment by kondziu** [comment]
Fixed by a0c7c024406a62e1bbcb84a39516d10bf7875b75. Or so I hope
